const u = (id, crop = 'faces,edges') =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=700&h=900&q=88&crop=${crop}`

export const PROFILES = [
  {
    id: 'luna',
    name: 'Luna',
    age: 19,
    city: 'cde',
    tags: {
      pt: ['Novinha', 'Hotel', 'PT/ES'],
      en: ['Young', 'Hotel', 'PT/ES'],
      es: ['Jovencita', 'Hotel', 'PT/ES'],
    },
    height: '1,67',
    vibe: {
      pt: 'Cara de safada, boca vermelha. Microcentro CDE.',
      en: 'Naughty face, red lips. CDE downtown.',
      es: 'Cara de diabla, labios rojos. Microcentro CDE.',
    },
    priceUsd: 350,
    whatsapp: '595981000001',
    photo: u('photo-1616683693504-3ea7e9ad6fec'),
    focus: 'center 22%',
  },
  {
    id: 'valentina',
    name: 'Valentina',
    age: 21,
    city: 'foz',
    tags: {
      pt: ['Premium', 'Motel', 'PT'],
      en: ['Premium', 'Motel', 'PT'],
      es: ['Premium', 'Motel', 'PT'],
    },
    height: '1,71',
    vibe: {
      pt: 'Corpo caro. Olhar que manda calar a boca.',
      en: 'Expensive body. Looks that shut you up.',
      es: 'Cuerpo caro. Mirada que te calla.',
    },
    priceUsd: 480,
    whatsapp: '554599000002',
    photo: u('photo-1515886657613-9f3515b0c78f'),
    focus: 'center 20%',
  },
  {
    id: 'sofia',
    name: 'Sofía',
    age: 18,
    city: 'cde',
    tags: {
      pt: ['Novinha', 'Apto', 'ES/PT'],
      en: ['Young', 'Apt', 'ES/PT'],
      es: ['Jovencita', 'Depto', 'ES/PT'],
    },
    height: '1,64',
    vibe: {
      pt: 'Recém 18, já cobra caro. San Blas.',
      en: 'Just 18, already expensive. San Blas.',
      es: 'Recién 18, ya cobra caro. San Blas.',
    },
    priceUsd: 320,
    whatsapp: '595981000003',
    photo: u('photo-1529626455594-4ff0802cfb7e'),
    focus: 'center 16%',
  },
  {
    id: 'marina',
    name: 'Marina',
    age: 22,
    city: 'foz',
    tags: {
      pt: ['VIP', 'Hotel', 'PT/EN'],
      en: ['VIP', 'Hotel', 'PT/EN'],
      es: ['VIP', 'Hotel', 'PT/EN'],
    },
    height: '1,69',
    vibe: {
      pt: 'Turista rico só. Não atende barato.',
      en: 'Rich tourists only. No cheap dates.',
      es: 'Solo turista con plata. Nada barato.',
    },
    priceUsd: 550,
    whatsapp: '554599000004',
    photo: u('photo-1496747611176-843222e1e57c'),
    focus: 'center 18%',
  },
  {
    id: 'camila',
    name: 'Camila',
    age: 20,
    city: 'puerto',
    tags: {
      pt: ['Safada', 'Hotel', 'ES'],
      en: ['Naughty', 'Hotel', 'ES'],
      es: ['Caliente', 'Hotel', 'ES'],
    },
    height: '1,66',
    vibe: {
      pt: 'Lado AR. Beijo sujo, horário flexível.',
      en: 'AR side. Dirty kiss, flexible hours.',
      es: 'Lado AR. Beso sucio, horario flexible.',
    },
    priceUsd: 380,
    whatsapp: '5493757000005',
    photo: u('photo-1487412720507-e7ab37603c6f'),
    focus: 'center 12%',
  },
  {
    id: 'bia',
    name: 'Bia',
    age: 19,
    city: 'hernandarias',
    tags: {
      pt: ['Novinha', 'Local', 'ES/PT'],
      en: ['Young', 'Local', 'ES/PT'],
      es: ['Jovencita', 'Local', 'ES/PT'],
    },
    height: '1,62',
    vibe: {
      pt: 'Cara de anjo, resto de puta cara.',
      en: 'Angel face, expensive everything else.',
      es: 'Cara de ángel, el resto de puta cara.',
    },
    priceUsd: 300,
    whatsapp: '595981000006',
    photo: u('photo-1534528741775-53994a69daeb'),
    focus: 'center 15%',
  },
  {
    id: 'raquel',
    name: 'Raquel',
    age: 23,
    city: 'cde',
    tags: {
      pt: ['Jantar', 'Noite', 'PT/ES'],
      en: ['Dinner', 'Night', 'PT/ES'],
      es: ['Cena', 'Noche', 'PT/ES'],
    },
    height: '1,73',
    vibe: {
      pt: 'Noite inteira. Valor de quem sabe o que vale.',
      en: 'Full night. Priced like she knows her worth.',
      es: 'Noche entera. Precio de quien se conoce.',
    },
    priceUsd: 700,
    whatsapp: '595981000007',
    photo: u('photo-1529139574466-a303027c1d8b'),
    focus: 'center 14%',
  },
  {
    id: 'giulia',
    name: 'Giulia',
    age: 20,
    city: 'foz',
    tags: {
      pt: ['Apto', 'Safada', 'PT'],
      en: ['Apt', 'Naughty', 'PT'],
      es: ['Depto', 'Caliente', 'PT'],
    },
    height: '1,68',
    vibe: {
      pt: 'Vila Portes. Olho no olho e já sabe o jogo.',
      en: 'Vila Portes. Eye contact and she owns the game.',
      es: 'Vila Portes. Mirada fija y ya sabe el juego.',
    },
    priceUsd: 420,
    whatsapp: '554599000008',
    photo: u('photo-1469334031218-e382a71b716b'),
    focus: 'center 20%',
  },
]
